import 'package:flutter/material.dart';

class AppLocalizations {
  final String locale;

  AppLocalizations(this.locale);

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Anzor AI',
      'studio_title': 'Prompt Generator Studio',
      'studio_subtitle': 'AI Prompt Generator Studio',
      'input_placeholder': 'Enter a simple idea (e.g., A warrior standing in rain...)',
      'btn_generate': 'Generate Expanded Prompt',
      'btn_generating': 'Generating prompt...',
      'tab_text_to_prompt': 'Text to Prompt',
      'tab_image_to_prompt': 'Image to Prompt',
      'art_style_selector': 'Art Style Selector',
      'quality_enhancers': 'Quality Enhancement Presets',
      'expanded_prompt_title': 'Expanded Prompt',
      'creative_enhancement_title': 'Creative Enhancement',
      'explanation_title': 'Prompt Explanation',
      'copy_success': 'Prompt copied to clipboard!',
      'copy_btn': 'Copy',
      'regenerate_btn': 'Regenerate',
      'edit_btn': 'Edit',
      'save_btn': 'Save',
      'styles_title': 'Select Art Styles (Multiple)',
      'presets_title': 'Select Presets',
      
      // Vision / Reverse engineering
      'vision_title': 'AI Image Reverse Engineering',
      'vision_instructions': 'Upload an image to reverse-engineer its style, composition, colors, and lighting into a reusable prompt template.',
      'btn_take_photo': 'Take Photo',
      'btn_upload_gallery': 'Upload Gallery',
      'vision_output_prompt': 'Reverse Engineered Prompt',
      'vision_output_composition': 'Composition & Layout',
      'vision_output_lighting': 'Lighting & Atmosphere',
      'vision_output_colors': 'Color Palette',
      'vision_output_style': 'Primary Art Style',
      'vision_no_image': 'No image selected. Please capture or upload one.',
      'vision_analyzing': 'Analyzing image features...',

      // Community
      'community_title': 'Community Hub',
      'community_subtitle': 'Trending prompts from the creative community',
      'tab_all': 'All',
      'tab_realistic': 'Realistic',
      'tab_anime': 'Anime',
      'tab_fantasy': 'Fantasy',
      'tab_nature': 'Nature',
      'tab_sci_fi': 'Sci-Fi',
      'tab_portrait': 'Portrait',
      'tab_architecture': 'Architecture',
      'tab_animals': 'Animals',
      'likes_count': 'likes',
      'prompt_details_title': 'Prompt Details',
      'btn_bookmark': 'Save to Collection',
      'btn_bookmarked': 'Saved',

      // Submit Screen
      'submit_title': 'Submit Prompt',
      'submit_subtitle': 'Contribute to the Anzor showcase',
      'field_title': 'Prompt Title',
      'field_description': 'Short Description',
      'field_full_prompt': 'Full Expanded Prompt',
      'field_category': 'Category',
      'field_tags': 'Tags (comma separated)',
      'btn_submit': 'Submit Prompt for Review',
      'submit_success': 'Prompt submitted successfully and is currently in moderation!',
      'error_fields': 'Please fill in all required fields.',

      // History
      'history_title': 'Generation History',
      'history_subtitle': 'Timeline of your generated creative prompts',
      'history_empty': 'No prompts generated yet. Start generating in the Studio!',

      // Profile & Collections
      'profile_title': 'My Profile',
      'profile_total_prompts': 'Total Prompts',
      'profile_contributions': 'Contributions',
      'profile_saved': 'Saved Prompts',
      'edit_profile': 'Edit Profile',
      'collections_title': 'Saved Collections',
      'btn_create_collection': 'Create Collection',
      'collection_name_hint': 'Enter collection name',
      'collection_created': 'Collection created!',
      'settings_title': 'Settings & Preferences',
      'settings_lang': 'Language',
      'settings_appearance': 'Appearance',
      'theme_dark': 'Dark Mode',
      'theme_light': 'Light Mode',
      'theme_system': 'System Theme',
      'setting_notifications': 'Push Notifications',
      'setting_autosave': 'Auto-save History',
      'setting_datasync': 'Cloud Data Sync',
      'gemini_api_key_label': 'Direct Gemini API Key (Optional)',
      'gemini_api_key_hint': 'Enter API key for standalone mode',
      
      // Admin Panel
      'admin_dashboard_title': 'Admin Dashboard',
      'admin_tab_moderation': 'Moderation Queue',
      'admin_tab_analytics': 'System Analytics',
      'admin_tab_logs': 'Real-Time Server Logs',
      'admin_btn_approve': 'Approve',
      'admin_btn_reject': 'Reject',
      'admin_btn_delete': 'Delete',
      'admin_status_pending': 'Pending Review',
      'admin_status_approved': 'Approved',
      'admin_status_rejected': 'Rejected',
      'admin_analytics_title': 'System Telemetry Metrics',
      'admin_uptime': 'Server Uptime',
      'admin_health': 'System Health',
      'admin_mem': 'Node Memory Usage',
      'admin_total_gens': 'Total AI Generations',
      'admin_avg_latency': 'Average Request Latency',
      'admin_errors': 'System Error Rate',
      'admin_logs_title': 'Live Server Activity Logs',
      'admin_sign_in_hint': 'Demo Admin Account Toggle',
      'admin_mode_enabled': 'Administrator Privileges Enabled',
      'admin_mode_disabled': 'Switched to Standard User Mode',
    },
    'ur_roman': {
      'app_title': 'Anzor AI',
      'studio_title': 'Prompt Generator Studio',
      'studio_subtitle': 'AI Prompt Generator Studio',
      'input_placeholder': 'Aik sada khayal likhein (jaise, Aik jangi barish me...)',
      'btn_generate': 'Wasee Shuda Prompt Banayein',
      'btn_generating': 'Prompt tayyar ho raha hai...',
      'tab_text_to_prompt': 'Likhayi Se Prompt',
      'tab_image_to_prompt': 'Tasveer Se Prompt',
      'art_style_selector': 'Fanni Andaz Select Karein',
      'quality_enhancers': 'Miyaar Ke Presets',
      'expanded_prompt_title': 'Wasee Shuda Prompt',
      'creative_enhancement_title': 'Takhleeqi Izafa',
      'explanation_title': 'Prompt Ki Wazaahat',
      'copy_success': 'Prompt clipboard par copy ho gaya!',
      'copy_btn': 'Copy',
      'regenerate_btn': 'Regenerate',
      'edit_btn': 'Edit',
      'save_btn': 'Save',
      'styles_title': 'Fanni Andaz Chunein (Ek se zyada)',
      'presets_title': 'Presets Chunein',
      
      // Vision / Reverse engineering
      'vision_title': 'AI Tasveer Reverse Engineering',
      'vision_instructions': 'Tasveer upload karein taake iska andaz, composition, rang, aur roshni aik reusable template me tabdeel kiya ja sake.',
      'btn_take_photo': 'Tasveer Kheenchein',
      'btn_upload_gallery': 'Gallery Se Chunein',
      'vision_output_prompt': 'Aks Se Bana Prompt',
      'vision_output_composition': 'Composition aur Layout',
      'vision_output_lighting': 'Roshni aur Mahool',
      'vision_output_colors': 'Rangon Ki Scheme',
      'vision_output_style': 'Bunyadi Fanni Andaz',
      'vision_no_image': 'Tasveer chuni nahi gayi. Pehle capture ya upload karein.',
      'vision_analyzing': 'Tasveer ka tajziya ho raha hai...',

      // Community
      'community_title': 'Community Hub',
      'community_subtitle': 'Community ke behtareen aur mashhoor prompts',
      'tab_all': 'Sab',
      'tab_realistic': 'Realistic',
      'tab_anime': 'Anime',
      'tab_fantasy': 'Fantasy',
      'tab_nature': 'Qudrat',
      'tab_sci_fi': 'Sci-Fi',
      'tab_portrait': 'Tasveer',
      'tab_architecture': 'Tameeraat',
      'tab_animals': 'Janwar',
      'likes_count': 'pasand',
      'prompt_details_title': 'Prompt Ki Tafseel',
      'btn_bookmark': 'Collection Me Save Karein',
      'btn_bookmarked': 'Saved',

      // Submit Screen
      'submit_title': 'Prompt Submit Karein',
      'submit_subtitle': 'Anzor showcase me apna hissa dalien',
      'field_title': 'Prompt Ka Unwaan',
      'field_description': 'Mukhtasar Tafseel',
      'field_full_prompt': 'Pura Wasee Shuda Prompt',
      'field_category': 'Category',
      'field_tags': 'Tags (comma laga kar likhein)',
      'btn_submit': 'Review Ke Liye Bhejein',
      'submit_success': 'Prompt submit ho gaya! Abhi iska review ho raha hai.',
      'error_fields': 'Meherbani kar ke tamam zaroori fields bharein.',

      // History
      'history_title': 'Generation History',
      'history_subtitle': 'Aapke banaye gaye prompts ki timeline',
      'history_empty': 'Abhi tak koi prompt nahi banaya gaya. Studio me shuru karein!',

      // Profile & Collections
      'profile_title': 'Mera Profile',
      'profile_total_prompts': 'Kul Prompts',
      'profile_contributions': 'Hissa Dari',
      'profile_saved': 'Saved Prompts',
      'edit_profile': 'Profile Edit Karein',
      'collections_title': 'Saved Collections',
      'btn_create_collection': 'Collection Banayein',
      'collection_name_hint': 'Collection ka naam likhein',
      'collection_created': 'Collection ban gayi!',
      'settings_title': 'Settings aur Preferences',
      'settings_lang': 'Zabaan (Language)',
      'settings_appearance': 'Appearance (Theme)',
      'theme_dark': 'Dark Mode',
      'theme_light': 'Light Mode',
      'theme_system': 'System Theme',
      'setting_notifications': 'Push Notifications',
      'setting_autosave': 'History Auto-Save',
      'setting_datasync': 'Cloud Data Sync',
      'gemini_api_key_label': 'Direct Gemini API Key (Ikhtiyaari)',
      'gemini_api_key_hint': 'Direct AI ke liye key dalein',
      
      // Admin Panel
      'admin_dashboard_title': 'Admin Dashboard',
      'admin_tab_moderation': 'Moderation Qataar',
      'admin_tab_analytics': 'System Analytics',
      'admin_tab_logs': 'Live Server Logs',
      'admin_btn_approve': 'Manzoor',
      'admin_btn_reject': 'Mustarad',
      'admin_btn_delete': 'Delete',
      'admin_status_pending': 'Ghaur Talab',
      'admin_status_approved': 'Manzoor Shuda',
      'admin_status_rejected': 'Mustarad Shuda',
      'admin_analytics_title': 'System Telemetry Metrics',
      'admin_uptime': 'Server Chalo Uptime',
      'admin_health': 'System Sehat',
      'admin_mem': 'Node Memory Istemal',
      'admin_total_gens': 'Kul AI Generations',
      'admin_avg_latency': 'Ausat Request Latency',
      'admin_errors': 'System Error Rate',
      'admin_logs_title': 'Live Server Activity Logs',
      'admin_sign_in_hint': 'Demo Admin Account Toggle',
      'admin_mode_enabled': 'Admin Ahdaat Faal Kar Diye Gae',
      'admin_mode_disabled': 'Aam Sarif Mode Par Chale Gae',
    }
  };

  String translate(String key) {
    return _localizedValues[locale]?[key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    final state = Localizations.localeOf(context);
    return AppLocalizations(state.languageCode == 'ur' ? 'ur_roman' : 'en');
  }
}
